server:
  port: 8088

spring:
  application:
    name: cfgo-test
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cfgo-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: cf123456
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.chenfei.cfgo.study.service.feign: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
