server:
  port: 8088

spring:
  application:
    name: cfgo-test
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cfgo-test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: cf123456
    driverClassName: com.mysql.cj.jdbc.Driver

  redis:
    host: 192.168.136.130
    port: 6379
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000

logging:
  level:
    com.chenfei.cfgo.study.service.feign: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
